# -*- coding: utf-8 -*-
# Ported verbatim from personalized-product-scanner/server/demoData.ts — do not diverge.
DEMO_PRODUCTS = [{'barcode': '3017620422003',
  'name': 'Nutella Hazelnut Spread with Cocoa',
  'brand': 'Ferrero',
  'type': 'food',
  'category': 'Spreads & Sweets',
  'image': 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=400&auto=format&fit=crop&q=80',
  'ingredientsText': 'Sugar, Palm Oil, Hazelnuts (13%), Skimmed Milk Powder (8.7%), Fat-Reduced Cocoa '
                     '(7.4%), Emulsifier: Lecithins (Soya), Vanillin.',
  'ingredientsList': ['Sugar',
                      'Palm Oil',
                      'Hazelnuts (13%)',
                      'Skimmed Milk Powder (8.7%)',
                      'Fat-Reduced Cocoa (7.4%)',
                      'Soya Lecithin',
                      'Vanillin'],
  'allergens': ['hazelnuts', 'milk', 'soy', 'tree nuts'],
  'labels': ['Vegetarian', 'Gluten Free'],
  'nutrition': {'energyKcal': 539,
                'sugars': 56.3,
                'fat': 30.9,
                'saturatedFat': 10.6,
                'proteins': 6.3,
                'carbohydrates': 57.5,
                'salt': 0.107,
                'sodium': 43,
                'novaGroup': 4,
                'nutriscoreGrade': 'e'}},
 {'barcode': '0028400064057',
  'name': "Lay's Classic Potato Chips",
  'brand': 'Frito-Lay',
  'type': 'food',
  'category': 'Snacks & Chips',
  'image': 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&auto=format&fit=crop&q=80',
  'ingredientsText': 'Potatoes, Vegetable Oil (Canola, Corn, Soybean, and/or Sunflower Oil), and Salt.',
  'ingredientsList': ['Potatoes', 'Vegetable Oil', 'Soybean Oil', 'Salt'],
  'allergens': ['soybean'],
  'labels': ['Vegan', 'Gluten-Free', 'Kosher'],
  'nutrition': {'energyKcal': 536,
                'sugars': 0.5,
                'fat': 35.7,
                'saturatedFat': 5.4,
                'proteins': 7.1,
                'carbohydrates': 53.6,
                'salt': 1.25,
                'sodium': 500,
                'novaGroup': 3,
                'nutriscoreGrade': 'c'}},
 {'barcode': '7340083437199',
  'name': 'Oatly Barista Edition Oat Milk',
  'brand': 'Oatly',
  'type': 'food',
  'category': 'Plant Milk',
  'image': 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&auto=format&fit=crop&q=80',
  'ingredientsText': 'Oat base (water, oats 10%), rapeseed oil, acidity regulator (dipotassium phosphate), '
                     'calcium carbonate, calcium phosphates, iodised salt, vitamins (D2, riboflavin, B12).',
  'ingredientsList': ['Water',
                      'Oats (10%)',
                      'Rapeseed Oil',
                      'Dipotassium Phosphate',
                      'Calcium Carbonate',
                      'Iodised Salt',
                      'Vitamin D2',
                      'Riboflavin',
                      'Vitamin B12'],
  'allergens': ['oats'],
  'labels': ['Vegan', 'Dairy-Free', 'Nut-Free', 'Non-GMO', 'Kosher'],
  'nutrition': {'energyKcal': 59,
                'sugars': 4,
                'fat': 3,
                'saturatedFat': 0.3,
                'proteins': 1,
                'carbohydrates': 6.6,
                'salt': 0.1,
                'sodium': 40,
                'novaGroup': 3,
                'nutriscoreGrade': 'b'}},
 {'barcode': '3337875597181',
  'name': 'CeraVe Hydrating Facial Cleanser',
  'brand': 'CeraVe',
  'type': 'cosmetic',
  'category': 'Skincare / Cleanser',
  'image': 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&auto=format&fit=crop&q=80',
  'ingredientsText': 'Aqua/Water, Glycerin, Cetearyl Alcohol, PEG-40 Stearate, Stearyl Alcohol, Potassium '
                     'Phosphate, Ceramide NP, Ceramide AP, Ceramide EOP, Carbomer, Glyceryl Stearate, '
                     'Behentrimonium Methosulfate, Sodium Lauroyl Lactylate, Sodium Hyaluronate, '
                     'Cholesterol, Phenoxyethanol, Disodium EDTA, Dipotassium Phosphate, Tocopherol, '
                     'Phytosphingosine, Xanthan Gum, Ethylhexylglycerin.',
  'ingredientsList': ['Aqua/Water',
                      'Glycerin',
                      'Cetearyl Alcohol',
                      'Ceramide NP',
                      'Ceramide AP',
                      'Ceramide EOP',
                      'Sodium Hyaluronate',
                      'Cholesterol',
                      'Phytosphingosine',
                      'Tocopherol'],
  'allergens': [],
  'labels': ['Fragrance-Free', 'Non-Comedogenic', 'Dermatologist Tested', 'Sensitive Skin Safe'],
  'cosmetic': {'category': 'Facial Cleanser',
               'comedogenicRating': 1,
               'hasFragrance': False,
               'hasParabens': False,
               'hasSulfates': False,
               'hasAlcohol': False,
               'hasRetinoids': False,
               'hasSalicylicAcid': False,
               'safetySummary': 'Gentle barrier-repairing cleanser with 3 essential ceramides and hyaluronic '
                                'acid. Fragrance-free and hypoallergenic.'}},
 {'barcode': '0769915190601',
  'name': 'The Ordinary Niacinamide 10% + Zinc 1%',
  'brand': 'The Ordinary / DECIEM',
  'type': 'cosmetic',
  'category': 'Skincare / Serum',
  'image': 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&auto=format&fit=crop&q=80',
  'ingredientsText': 'Aqua (Water), Niacinamide, Pentylene Glycol, Zinc PCA, Dimethyl Isosorbide, Tamarindus '
                     'Indica Seed Gum, Xanthan Gum, Isoceteth-20, Ethoxydiglycol, Phenoxyethanol, '
                     'Chlorphenesin.',
  'ingredientsList': ['Aqua',
                      'Niacinamide (10%)',
                      'Pentylene Glycol',
                      'Zinc PCA (1%)',
                      'Tamarindus Indica Seed Gum',
                      'Phenoxyethanol'],
  'allergens': [],
  'labels': ['Vegan', 'Cruelty-Free', 'Oil-Free', 'Silicone-Free', 'Fragrance-Free'],
  'cosmetic': {'category': 'Facial Treatment Serum',
               'comedogenicRating': 0,
               'hasFragrance': False,
               'hasParabens': False,
               'hasSulfates': False,
               'hasAlcohol': False,
               'hasRetinoids': False,
               'hasSalicylicAcid': False,
               'safetySummary': 'High-strength vitamin and mineral blemish formula with minimal irritation '
                                'profile.'}},
 {'barcode': '0850000000018',
  'name': 'Advanced Retinol 1.0 Night Renewal Cream',
  'brand': 'DermaTech Lab',
  'type': 'cosmetic',
  'category': 'Skincare / Anti-Aging',
  'image': 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400&auto=format&fit=crop&q=80',
  'ingredientsText': 'Aqua, Caprylic/Capric Triglyceride, Glycerin, Cetearyl Alcohol, Retinol, Dimethicone, '
                     'Polysorbate 20, Fragrance (Parfum), Linalool, Limonene, Methylparaben, Propylparaben, '
                     'BHT.',
  'ingredientsList': ['Aqua',
                      'Caprylic/Capric Triglyceride',
                      'Glycerin',
                      'Retinol',
                      'Fragrance (Parfum)',
                      'Linalool',
                      'Limonene',
                      'Methylparaben',
                      'Propylparaben'],
  'allergens': ['fragrance', 'linalool', 'limonene', 'parabens', 'retinoid'],
  'labels': ['Anti-Aging Formula'],
  'cosmetic': {'category': 'Night Treatment Cream',
               'comedogenicRating': 2,
               'hasFragrance': True,
               'hasParabens': True,
               'hasSulfates': False,
               'hasAlcohol': False,
               'hasRetinoids': True,
               'hasSalicylicAcid': False,
               'safetySummary': 'Potent active retinoid formula. Contains synthetic fragrance and paraben '
                                'preservatives.'}}]
