"""Curated class-level drug-drug interaction rules.

Sources: FDA product labeling (boxed warnings / contraindications /
warnings sections), widely established clinical pharmacology.
These are informational rules for a consumer reference tool, not
prescriptive medical advice.
"""

# severity: major | moderate | minor
DRUG_DRUG_RULES = [
    # --- Anticoagulants ---
    dict(cls_a="anticoagulantes", cls_b="aines", severity="major",
         effect="Markedly increased risk of bleeding, including gastrointestinal and intracranial hemorrhage.",
         mechanism="NSAIDs impair platelet function and cause GI mucosal injury while warfarin-type anticoagulants reduce clotting factor synthesis; risk is additive.",
         source="FDA warfarin and NSAID labeling"),
    dict(cls_a="anticoagulantes", cls_b="antiplaquetarios", severity="major",
         effect="Major bleeding risk when anticoagulants are combined with antiplatelet agents.",
         mechanism="Additive inhibition of hemostasis (clotting factor synthesis plus platelet inhibition).",
         source="FDA anticoagulant labeling"),
    dict(cls_a="anticoagulantes", cls_b="antifungicos", severity="major",
         effect="Elevated INR and serious bleeding risk.",
         mechanism="Azole antifungals (ketoconazole, fluconazole, itraconazole) inhibit CYP2C9/CYP3A4 metabolism of warfarin.",
         source="FDA azole antifungal and warfarin labeling"),
    dict(cls_a="anticoagulantes", cls_b="macrolidos", severity="moderate",
         effect="Increased anticoagulant effect and INR elevation.",
         mechanism="Clarithromycin and erythromycin inhibit CYP3A4-mediated warfarin metabolism.",
         source="FDA macrolide labeling"),
    dict(cls_a="anticoagulantes", cls_b="tiroideos", severity="moderate",
         effect="Enhanced anticoagulant effect; may require warfarin dose reduction.",
         mechanism="Thyroid hormone accelerates catabolism of vitamin-K-dependent clotting factors.",
         source="FDA levothyroxine and warfarin labeling"),
    dict(cls_a="anticoagulantes", cls_b="paracetamol", severity="moderate",
         effect="INR elevation with sustained high-dose acetaminophen use.",
         mechanism="A metabolite of acetaminophen inhibits vitamin K dependent carboxylase; risk increases with doses above ~2 g/day over several days.",
         source="FDA warfarin labeling"),
    dict(cls_a="anticoagulantes", cls_b="antibioticos", severity="moderate",
         effect="Possible enhanced anticoagulation (fluoroquinolones) or altered gut flora effect.",
         mechanism="Fluoroquinolones such as ciprofloxacin can inhibit warfarin metabolism; broad-spectrum antibiotics reduce vitamin K producing gut flora.",
         source="FDA fluoroquinolone labeling"),
    dict(cls_a="anticoagulantes", cls_b="antiarritmicos", severity="major",
         effect="Pronounced INR elevation and bleeding risk with amiodarone.",
         mechanism="Amiodarone inhibits CYP2C9 and CYP1A2, reducing warfarin clearance.",
         source="FDA amiodarone labeling"),
    dict(cls_a="anticoagulantes", cls_b="corticosteroides", severity="moderate",
         effect="Variable anticoagulant effect; GI bleeding risk may increase.",
         mechanism="Corticosteroids can both potentiate anticoagulation and irritate the GI mucosa.",
         source="FDA corticosteroid labeling"),
    # --- Serotonergic / CNS ---
    dict(cls_a="isrs", cls_b="imao", severity="major",
         effect="Serotonin syndrome: agitation, hyperthermia, rigidity; potentially fatal. Contraindicated combination.",
         mechanism="Additive serotonergic activity; MAOIs require a 14-day washout before starting SSRIs.",
         source="FDA SSRI and MAOI labeling (boxed warning)"),
    dict(cls_a="isrsn", cls_b="imao", severity="major",
         effect="Serotonin syndrome; contraindicated combination.",
         mechanism="Additive serotonergic activity with monoamine oxidase inhibition.",
         source="FDA SNRI and MAOI labeling (boxed warning)"),
    dict(cls_a="triciclicos", cls_b="imao", severity="major",
         effect="Serotonin syndrome or hypertensive crisis; contraindicated combination.",
         mechanism="Blockade of monoamine reuptake plus inhibition of monoamine breakdown.",
         source="FDA TCA and MAOI labeling"),
    dict(cls_a="isrs", cls_b="antimigrañosos", severity="moderate",
         effect="Serotonin syndrome with triptans.",
         mechanism="Additive serotonin receptor stimulation.",
         source="FDA triptan labeling"),
    dict(cls_a="isrs", cls_b="opioides", severity="moderate",
         effect="Serotonin syndrome; with tramadol also increased seizure risk.",
         mechanism="Tramadol inhibits serotonin reuptake and lowers seizure threshold; additive serotonergic effect.",
         source="FDA tramadol labeling"),
    dict(cls_a="imao", cls_b="antitusivos", severity="major",
         effect="Serotonin syndrome with dextromethorphan.",
         mechanism="Dextromethorphan is a serotonin reuptake inhibitor; additive with MAOI.",
         source="FDA MAOI labeling"),
    dict(cls_a="isrs", cls_b="antitusivos", severity="moderate",
         effect="Serotonin syndrome with dextromethorphan.",
         mechanism="Additive serotonin reuptake inhibition.",
         source="FDA dextromethorphan labeling"),
    dict(cls_a="litio", cls_b="isrs", severity="moderate",
         effect="Serotonin syndrome; lithium levels may also change.",
         mechanism="Additive serotonergic activity.",
         source="FDA lithium labeling"),
    dict(cls_a="benzodiacepinas", cls_b="opioides", severity="major",
         effect="Profound sedation, respiratory depression, coma, death. Boxed warning.",
         mechanism="Additive CNS and respiratory depressant effects.",
         source="FDA opioid and benzodiazepine labeling (boxed warning)"),
    dict(cls_a="opioides", cls_b="gabapentinoides", severity="major",
         effect="Respiratory depression and CNS depression; boxed warning.",
         mechanism="Additive respiratory depressant effects.",
         source="FDA opioid and gabapentinoid labeling (boxed warning)"),
    dict(cls_a="opioides", cls_b="hipnoticos", severity="major",
         effect="Profound sedation and respiratory depression.",
         mechanism="Additive CNS depressant effects of opioids and z-drugs.",
         source="FDA zolpidem and opioid labeling"),
    dict(cls_a="opioides", cls_b="antihistaminicos", severity="moderate",
         effect="Additive sedation, dizziness, psychomotor impairment.",
         mechanism="Combined CNS depressant effects.",
         source="FDA antihistamine labeling"),
    dict(cls_a="opioides", cls_b="relajantes_musculares", severity="moderate",
         effect="Additive CNS depression, sedation, falls.",
         mechanism="Combined CNS depressant effects.",
         source="FDA muscle relaxant labeling"),
    dict(cls_a="benzodiacepinas", cls_b="hipnoticos", severity="moderate",
         effect="Additive sedation and impairment.",
         mechanism="Both potentiate GABAergic transmission.",
         source="FDA benzodiazepine and z-drug labeling"),
    dict(cls_a="anticolinergicos", cls_b="antihistaminicos", severity="moderate",
         effect="High anticholinergic burden: confusion, dry mouth, constipation, urinary retention; risky in older adults.",
         mechanism="Additive muscarinic receptor blockade.",
         source="FDA anticholinergic drug labeling; AGS Beers criteria"),
    # --- Statins ---
    dict(cls_a="estatinas", cls_b="antifungicos", severity="major",
         effect="Myopathy and rhabdomyolysis risk, especially with simvastatin and lovastatin.",
         mechanism="Azole antifungals inhibit CYP3A4, raising statin plasma levels.",
         source="FDA statin labeling"),
    dict(cls_a="estatinas", cls_b="macrolidos", severity="major",
         effect="Myopathy and rhabdomyolysis risk with clarithromycin/erythromycin.",
         mechanism="CYP3A4 inhibition raises statin exposure.",
         source="FDA statin and macrolide labeling"),
    dict(cls_a="estatinas", cls_b="antiarritmicos", severity="major",
         effect="Myopathy risk with amiodarone (marked for simvastatin; dose limits apply).",
         mechanism="Amiodarone inhibits CYP3A4-mediated statin metabolism.",
         source="FDA amiodarone and simvastatin labeling"),
    # --- Digoxin / Lithium / Methotrexate / Theophylline ---
    dict(cls_a="digoxina", cls_b="antiarritmicos", severity="major",
         effect="Digoxin toxicity: nausea, arrhythmias, visual changes.",
         mechanism="Amiodarone inhibits P-glycoprotein, doubling digoxin levels.",
         source="FDA digoxin and amiodarone labeling"),
    dict(cls_a="digoxina", cls_b="diureticos", severity="moderate",
         effect="Digoxin toxicity if hypokalemia or hypomagnesemia develops.",
         mechanism="Loop and thiazide diuretics deplete potassium and magnesium, sensitizing the myocardium to digoxin.",
         source="FDA digoxin labeling"),
    dict(cls_a="digoxina", cls_b="macrolidos", severity="moderate",
         effect="Elevated digoxin levels and toxicity risk.",
         mechanism="Macrolides inhibit P-glycoprotein-mediated digoxin efflux.",
         source="FDA digoxin and macrolide labeling"),
    dict(cls_a="litio", cls_b="aines", severity="major",
         effect="Lithium toxicity: tremor, ataxia, confusion, kidney injury.",
         mechanism="NSAIDs reduce renal clearance of lithium.",
         source="FDA lithium labeling"),
    dict(cls_a="litio", cls_b="diureticos", severity="major",
         effect="Lithium toxicity with thiazide diuretics.",
         mechanism="Thiazides increase proximal tubular lithium reabsorption.",
         source="FDA lithium labeling"),
    dict(cls_a="litio", cls_b="antihipertensivos", severity="moderate",
         effect="Rising lithium levels with ACE inhibitors (e.g. enalapril).",
         mechanism="ACE inhibitors reduce sodium load and lithium clearance.",
         source="FDA lithium and ACE inhibitor labeling"),
    dict(cls_a="metotrexato_rx", cls_b="aines", severity="major",
         effect="Methotrexate toxicity: myelosuppression, mucositis, kidney injury.",
         mechanism="NSAIDs reduce renal elimination of methotrexate.",
         source="FDA methotrexate labeling"),
    dict(cls_a="teofilina", cls_b="macrolidos", severity="moderate",
         effect="Theophylline toxicity: nausea, tachycardia, seizures.",
         mechanism="Macrolides inhibit CYP1A2/3A4 metabolism of theophylline.",
         source="FDA theophylline and macrolide labeling"),
    dict(cls_a="teofilina", cls_b="antibioticos", severity="moderate",
         effect="Theophylline toxicity with fluoroquinolones.",
         mechanism="Ciprofloxacin and similar agents inhibit theophylline metabolism.",
         source="FDA theophylline and fluoroquinolone labeling"),
    # --- Metabolic / renal / misc ---
    dict(cls_a="anticonceptivos", cls_b="anticonvulsivantes", severity="moderate",
         effect="Reduced contraceptive efficacy; breakthrough bleeding; unintended pregnancy risk.",
         mechanism="Enzyme-inducing anticonvulsants (carbamazepine, phenytoin) accelerate estrogen/progestin metabolism.",
         source="FDA oral contraceptive labeling"),
    dict(cls_a="antihipertensivos", cls_b="aines", severity="moderate",
         effect="Reduced antihypertensive effect; increased risk of kidney injury, especially with ACE inhibitors/ARBs or diuretics.",
         mechanism="NSAIDs inhibit vasodilatory prostaglandins and promote sodium retention.",
         source="FDA NSAID labeling"),
    dict(cls_a="omeprazol", cls_b="antiplaquetarios", severity="moderate",
         effect="Reduced antiplatelet effect of clopidogrel; cardiovascular risk may increase.",
         mechanism="Omeprazole inhibits CYP2C19, which activates clopidogrel.",
         source="FDA clopidogrel labeling"),
    dict(cls_a="antifungicos", cls_b="benzodiacepinas", severity="moderate",
         effect="Prolonged sedation with triazolam, midazolam, alprazolam.",
         mechanism="Azole antifungals inhibit CYP3A4 metabolism of benzodiazepines.",
         source="FDA azole antifungal labeling"),
    dict(cls_a="alfa_bloqueantes", cls_b="vasodilatadores", severity="moderate",
         effect="Additive hypotension and dizziness when combined with PDE5 inhibitors.",
         mechanism="Combined vasodilation; PDE5 inhibitors potentiate alpha-blocker effects.",
         source="FDA PDE5 inhibitor labeling"),
    dict(cls_a="antidiabeticos", cls_b="betabloqueantes", severity="moderate",
         effect="Masked symptoms of hypoglycemia (palpitations, tremor) and delayed recovery.",
         mechanism="Beta-blockade blunts adrenergic warning signs of low blood sugar.",
         source="FDA beta-blocker labeling"),
    dict(cls_a="antidiabeticos_sglt2", cls_b="diureticos", severity="moderate",
         effect="Volume depletion, hypotension, and risk of acute kidney injury.",
         mechanism="Additive osmotic and loop diuresis.",
         source="FDA SGLT2 inhibitor labeling"),
    dict(cls_a="antipsicoticos", cls_b="antiemeticos", severity="moderate",
         effect="Extrapyramidal symptoms and dystonic reactions with metoclopramide.",
         mechanism="Additive dopamine D2 receptor blockade.",
         source="FDA metoclopramide labeling"),
    dict(cls_a="tiroideos", cls_b="omeprazol", severity="moderate",
         effect="Reduced levothyroxine absorption and hypothyroid symptoms.",
         mechanism="PPIs raise gastric pH, reducing dissolution/absorption of levothyroxine.",
         source="FDA levothyroxine labeling"),
    dict(cls_a="corticosteroides", cls_b="aines", severity="moderate",
         effect="Increased risk of GI ulceration and bleeding.",
         mechanism="Additive GI mucosal injury.",
         source="FDA NSAID labeling"),
    dict(cls_a="macrolidos", cls_b="anticonvulsivantes", severity="moderate",
         effect="Carbamazepine toxicity: dizziness, ataxia, diplopia.",
         mechanism="Macrolides inhibit CYP3A4 metabolism of carbamazepine.",
         source="FDA carbamazepine and macrolide labeling"),
    dict(cls_a="bifosfonatos", cls_b="aines", severity="minor",
         effect="Additive GI irritation.",
         mechanism="Both agents can irritate the upper GI mucosa.",
         source="FDA bisphosphonate labeling"),
    dict(cls_a="antirretrovirales", cls_b="omeprazol", severity="moderate",
         effect="Reduced levels of some antiretrovirals (e.g. atazanavir), risking treatment failure.",
         mechanism="PPIs raise gastric pH, impairing absorption of pH-dependent antiretrovirals.",
         source="FDA antiretroviral labeling"),
]

# Drug-level rules (more specific than class-level)
DRUG_LEVEL_RULES = [
    dict(drug_a="nitroglycerin", drug_b="sildenafil", severity="major",
         effect="Severe hypotension, syncope, myocardial infarction. Contraindicated combination.",
         mechanism="PDE5 inhibitors potentiate the vasodilatory effect of nitrates via cGMP accumulation.",
         source="FDA sildenafil and nitroglycerin labeling (contraindication)"),
    dict(drug_a="nitroglycerin", drug_b="tadalafil", severity="major",
         effect="Severe hypotension. Contraindicated combination.",
         mechanism="PDE5 inhibition potentiates nitrate-induced vasodilation.",
         source="FDA tadalafil labeling (contraindication)"),
    dict(drug_a="isosorbide", drug_b="sildenafil", severity="major",
         effect="Severe hypotension. Contraindicated combination.",
         mechanism="PDE5 inhibition potentiates nitrate-induced vasodilation.",
         source="FDA sildenafil labeling (contraindication)"),
    dict(drug_a="isosorbide", drug_b="tadalafil", severity="major",
         effect="Severe hypotension. Contraindicated combination.",
         mechanism="PDE5 inhibition potentiates nitrate-induced vasodilation.",
         source="FDA tadalafil labeling (contraindication)"),
    dict(drug_a="omeprazole", drug_b="clopidogrel", severity="moderate",
         effect="Reduced clopidogrel activation; consider pantoprazole instead.",
         mechanism="CYP2C19 inhibition by omeprazole/esomeprazole.",
         source="FDA clopidogrel labeling"),
    dict(drug_a="esomeprazole", drug_b="clopidogrel", severity="moderate",
         effect="Reduced clopidogrel activation; consider pantoprazole instead.",
         mechanism="CYP2C19 inhibition by omeprazole/esomeprazole.",
         source="FDA clopidogrel labeling"),
    dict(drug_a="tramadol", drug_b="fluoxetine", severity="major",
         effect="Serotonin syndrome and increased seizure risk.",
         mechanism="Additive serotonergic activity; fluoxetine inhibits tramadol metabolism via CYP2D6.",
         source="FDA tramadol labeling"),
    dict(drug_a="warfarin", drug_b="celecoxib", severity="major",
         effect="Increased bleeding risk and INR elevation.",
         mechanism="Celecoxib inhibits CYP2C9-mediated warfarin metabolism and impairs platelet function.",
         source="FDA celecoxib labeling"),
]
