"""Drug-food interaction rules curated from FDA drug labeling (public knowledge).

Same pattern as drug_drug_seed.py: public-domain knowledge from official
labels (grapefruit boxed warnings, alcohol contraindications, warfarin
vitamin-K guidance, MAOI tyramine boxed warning, etc.). trust=1.0 (FDA tier).

Foods are first-class matchable entities (kind="food") so users can add
"grapefruit" or "alcohol" to their cabinet and get food interaction checks.
"""
# food id -> display name + aliases (aliases normalized by the engine)
FOODS = [
    dict(id="grapefruit", name="Grapefruit", aliases=["grapefruit juice", "pomelo", "seville orange"]),
    dict(id="alcohol", name="Alcohol", aliases=["ethanol", "beer", "wine", "liquor", "spirits", "binge drinking"]),
    dict(id="vitamin_k_foods", name="Vitamin K foods", aliases=["leafy greens", "kale", "spinach", "broccoli", "brussels sprouts", "collard greens", "green tea"]),
    dict(id="dairy", name="Dairy", aliases=["milk", "cheese", "yogurt", "calcium", "calcium-rich foods", "calcium supplements"]),
    dict(id="caffeine", name="Caffeine", aliases=["coffee", "tea", "energy drinks", "caffeinated beverages"]),
    dict(id="tyramine_foods", name="Tyramine-rich foods", aliases=["aged cheese", "cured meats", "fermented foods", "soy sauce", "sauerkraut", "aged foods"]),
    dict(id="potassium_foods", name="Potassium-rich foods", aliases=["potassium", "bananas", "oranges", "salt substitutes", "potassium supplements", "coconut water"]),
    dict(id="licorice", name="Licorice", aliases=["glycyrrhiza", "black licorice"]),
    dict(id="high_fiber", name="High-fiber foods", aliases=["bran", "fiber supplements", "whole grains", "oatmeal", "psyllium"]),
    dict(id="charred_meat", name="Charred meat", aliases=["grilled meat", "barbecue", "bbq", "charcoal-grilled"]),
]

DRUG_FOOD_RULES = [
    # --- Grapefruit (CYP3A4 inhibition) ---
    dict(cls_a="estatinas", food="grapefruit", severity="major",
         effect="Grapefruit markedly raises simvastatin, lovastatin and atorvastatin blood levels, increasing myopathy and rhabdomyolysis risk.",
         mechanism="Furanocoumarins in grapefruit irreversibly inhibit intestinal CYP3A4.",
         source="FDA simvastatin and atorvastatin labeling"),
    dict(cls_a="inmunosupresores", food="grapefruit", severity="major",
         effect="Elevated cyclosporine and tacrolimus levels with risk of nephrotoxicity.",
         mechanism="Intestinal CYP3A4 inhibition raises drug exposure.",
         source="FDA tacrolimus and cyclosporine labeling"),
    dict(cls_a="benzodiacepinas", food="grapefruit", severity="moderate",
         effect="Increased sedation and psychomotor impairment (especially triazolam, midazolam, diazepam).",
         mechanism="CYP3A4 inhibition slows benzodiazepine metabolism.",
         source="FDA benzodiazepine labeling"),
    dict(cls_a="antiarritmicos", food="grapefruit", severity="moderate",
         effect="Raised amiodarone and dronedarone levels with risk of toxicity.",
         mechanism="CYP3A4 inhibition reduces clearance.",
         source="FDA amiodarone labeling"),
    dict(cls_a="antihipertensivos", food="grapefruit", severity="moderate",
         effect="Higher felodipine/nifedipine-type calcium channel blocker levels causing hypotension and edema.",
         mechanism="CYP3A4 inhibition reduces first-pass metabolism.",
         source="FDA calcium channel blocker labeling"),
    dict(cls_a="vasodilatadores", food="grapefruit", severity="moderate",
         effect="Elevated sildenafil and tadalafil levels; more side effects (headache, hypotension).",
         mechanism="CYP3A4 inhibition.",
         source="FDA PDE5 inhibitor labeling"),
    dict(cls_a="anticonceptivos", food="grapefruit", severity="minor",
         effect="Slightly increased estrogen exposure; possible breast tenderness.",
         mechanism="CYP3A4 inhibition of estrogen metabolism.",
         source="FDA oral contraceptive labeling"),
    # --- Alcohol ---
    dict(cls_a="benzodiacepinas", food="alcohol", severity="major",
         effect="Profound sedation, respiratory depression, impaired coordination; fatal overdose risk. Boxed warning.",
         mechanism="Additive CNS and respiratory depression.",
         source="FDA benzodiazepine labeling (boxed warning)"),
    dict(cls_a="opioides", food="alcohol", severity="major",
         effect="Respiratory depression, coma and death. Boxed warning.",
         mechanism="Additive CNS and respiratory depressant effects.",
         source="FDA opioid labeling (boxed warning)"),
    dict(cls_a="hipnoticos", food="alcohol", severity="major",
         effect="Enhanced sedation, complex sleep behaviors, overdose risk.",
         mechanism="Additive GABAergic CNS depression.",
         source="FDA zolpidem labeling"),
    dict(cls_a="paracetamol", food="alcohol", severity="major",
         effect="Heavy alcohol use increases acetaminophen liver injury risk even at normal doses.",
         mechanism="Alcohol induces CYP2E1, increasing the hepatotoxic NAPQI metabolite.",
         source="FDA acetaminophen labeling (boxed warning)"),
    dict(cls_a="gabapentinoides", food="alcohol", severity="major",
         effect="Respiratory depression and CNS depression. Boxed warning.",
         mechanism="Additive CNS depressant effects.",
         source="FDA gabapentin/pregabalin labeling (boxed warning)"),
    dict(cls_a="antidiabeticos", food="alcohol", severity="major",
         effect="Hypoglycemia (sulfonylureas) or lactic acidosis (metformin); alcohol impairs gluconeogenesis.",
         mechanism="Alcohol suppresses hepatic glucose output and extends sulfonylurea effect.",
         source="FDA metformin and sulfonylurea labeling"),
    dict(cls_a="antibioticos", food="alcohol", severity="moderate",
         effect="Disulfiram-like reaction with metronidazole: flushing, nausea, vomiting, tachycardia.",
         mechanism="Metronidazole inhibits aldehyde dehydrogenase.",
         source="FDA metronidazole labeling"),
    dict(cls_a="isrs", food="alcohol", severity="moderate",
         effect="Increased sedation and worsened depression control.",
         mechanism="Additive CNS effects; alcohol disrupts antidepressant response.",
         source="FDA SSRI labeling"),
    dict(cls_a="antihistaminicos", food="alcohol", severity="moderate",
         effect="Enhanced drowsiness and impaired driving.",
         mechanism="Additive sedation.",
         source="FDA antihistamine labeling"),
    # --- Vitamin K foods ---
    dict(cls_a="anticoagulantes", food="vitamin_k_foods", severity="major",
         effect="Vitamin K-rich foods (kale, spinach, green tea) reduce warfarin effect, risking clots. Keep intake consistent.",
         mechanism="Vitamin K counteracts warfarin's inhibition of clotting factor synthesis.",
         source="FDA warfarin labeling"),
    # --- Dairy / calcium ---
    dict(cls_a="tiroideos", food="dairy", severity="moderate",
         effect="Milk and calcium reduce levothyroxine absorption, risking hypothyroid symptoms.",
         mechanism="Calcium binds levothyroxine in the gut.",
         source="FDA levothyroxine labeling"),
    dict(cls_a="antibioticos", food="dairy", severity="moderate",
         effect="Milk and calcium cut ciprofloxacin-type antibiotic absorption; take 2h apart.",
         mechanism="Divalent cations chelate quinolones.",
         source="FDA ciprofloxacin labeling"),
    dict(cls_a="bifosfonatos", food="dairy", severity="moderate",
         effect="Milk/dairy blocks alendronate absorption, reducing bone protection.",
         mechanism="Calcium chelates bisphosphonates.",
         source="FDA alendronate labeling"),
    # --- Caffeine ---
    dict(cls_a="teofilina", food="caffeine", severity="moderate",
         effect="Additive stimulant effects: jitteriness, tachycardia, insomnia.",
         mechanism="Caffeine and theophylline are both methylxanthines.",
         source="FDA theophylline labeling"),
    dict(cls_a="antibioticos", food="caffeine", severity="moderate",
         effect="Ciprofloxacin slows caffeine clearance, causing nervousness and insomnia.",
         mechanism="CYP1A2 inhibition.",
         source="FDA ciprofloxacin labeling"),
    dict(cls_a="imao", food="caffeine", severity="moderate",
         effect="Large caffeine doses can raise blood pressure; risk of arrhythmia.",
         mechanism="Catecholamine potentiation.",
         source="FDA MAOI labeling"),
    # --- Tyramine ---
    dict(cls_a="imao", food="tyramine_foods", severity="major",
         effect="Hypertensive crisis: severe headache, palpitations, stroke risk. Contraindicated. Boxed warning.",
         mechanism="Tyramine displaces norepinephrine; MAO inhibition prevents its breakdown.",
         source="FDA MAOI labeling (boxed warning)"),
    # --- Potassium ---
    dict(cls_a="antihipertensivos", food="potassium_foods", severity="moderate",
         effect="ACE inhibitors/ARBs plus high potassium intake can cause hyperkalemia and arrhythmias.",
         mechanism="Reduced aldosterone raises potassium retention.",
         source="FDA ACE inhibitor labeling"),
    dict(cls_a="diureticos", food="potassium_foods", severity="moderate",
         effect="Potassium-sparing diuretics (spironolactone) plus potassium foods risk hyperkalemia.",
         mechanism="Additive potassium retention.",
         source="FDA spironolactone labeling"),
    # --- Licorice ---
    dict(cls_a="antihipertensivos", food="licorice", severity="moderate",
         effect="Licorice raises blood pressure and can reverse antihypertensive effect.",
         mechanism="Glycyrrhizin inhibits 11-beta-HSD2, causing mineralocorticoid excess.",
         source="Public knowledge; FDA potassium guidance"),
    dict(cls_a="digoxina", food="licorice", severity="moderate",
         effect="Licorice-induced potassium loss raises digoxin toxicity risk.",
         mechanism="Hypokalemia sensitizes the myocardium to digoxin.",
         source="FDA digoxin labeling"),
    # --- High fiber ---
    dict(cls_a="tiroideos", food="high_fiber", severity="moderate",
         effect="High-fiber meals reduce levothyroxine absorption.",
         mechanism="Fiber binds the hormone in the gut.",
         source="FDA levothyroxine labeling"),
    dict(cls_a="digoxina", food="high_fiber", severity="minor",
         effect="High-fiber meals can slightly reduce digoxin absorption.",
         mechanism="Fiber binding reduces bioavailability.",
         source="FDA digoxin labeling"),
    # --- Charred meat ---
    dict(cls_a="teofilina", food="charred_meat", severity="moderate",
         effect="Charcoal-grilled meat lowers theophylline levels, reducing asthma control.",
         mechanism="Polycyclic hydrocarbons induce CYP1A2.",
         source="FDA theophylline labeling"),
    # --- Anticoagulants + green tea (in vitamin K foods aliases) handled above ---
]
